language: ruby
rvm:
  - 2.3.0
before_script:
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - psql -c 'create database cardboard;' -U postgres
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
script:
  - bundle exec rubocop
  - bundle exec rspec
